# Stage 1: Build the Next.js app
FROM node:14 AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your app's source code
COPY . .

# Build the Next.js app
RUN npm run build

# Stage 2: Run the app
FROM node:14-alpine

# Set the working directory
WORKDIR /app

# Copy the build from the builder stage
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# Set the environment variable to production
ENV NODE_ENV production

# Expose the port the app runs on
EXPOSE 3000

# Run the Next.js start script
CMD ["npm", "start"]
